variables:
  azureSubscription: 'AZR-RWD-PRD1'
  docker.imageName: 'eprpaymentmopup'
  acr.azureContainerRegistryName: 'prdrwdinfac1401'
  acr.repositoryName: 'eprpaymentmopuprepository'
  serviceName: 'prdrwdwebwa1425'